### ISSUE TITLE
Update Manta to hard code version

### ISSUE THREAD

**Issue by jharenza** [kids-first/kf-somatic-workflow#18]
Currently coded to pull latest: https://github.com/kids-first/kf-somatic-workflow/blob/master/tools/manta.cwl

**Comment by migbro** [comment]
Docker build was called "latest", but versioning actually hard-coded to intended v1.4.0.  Will create updated/clearer docker build and point to that one

**Comment by migbro** [comment]
PR https://github.com/kids-first/kf-somatic-workflow/pull/37 has addressed this.
